spring:

  datasource:
    driverClassName : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurantorderingsystem?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.MySQL5InnoDBDialect



security:
  basic:
    enabled: false
