spring:

  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurantorderingsystem?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234
  jpa:
      properties:
        hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.ddl-auto : update


security:
  basic:
    enabled: false
